services:
  postal:
    build: .
    depends_on:
      - mariadb
    ports:
      - "5000:5000"
      - "25:25"
    volumes:
      - postal-config:/config
    environment:
      POSTAL_WEB_HOSTNAME: ${POSTAL_WEB_HOSTNAME}
      POSTAL_WEB_PROTOCOL: https
      POSTAL_SMTP_HOSTNAME: ${POSTAL_SMTP_HOSTNAME}
      MAIN_DB_HOST: mariadb
      MAIN_DB_PORT: 3306
      MAIN_DB_USERNAME: postal
      MAIN_DB_PASSWORD: ${DB_PASSWORD}
      MAIN_DB_DATABASE: postal
      MESSAGE_DB_HOST: mariadb
      MESSAGE_DB_PORT: 3306
      MESSAGE_DB_USERNAME: postal
      MESSAGE_DB_PASSWORD: ${DB_PASSWORD}
      RAILS_SECRET_KEY: ${RAILS_SECRET_KEY}
      POSTAL_SIGNING_KEY: ${POSTAL_SIGNING_KEY}
    restart: unless-stopped

  mariadb:
    image: mariadb:10.11
    restart: always
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: postal
      MARIADB_USER: postal
      MARIADB_PASSWORD: ${DB_PASSWORD}

volumes:
  postal-config:
  mariadb-data:
